// Krown Properties — Project Data
// Images are now loaded from /img folder

var PROJECTS = {
  arundel: {
    name: '46 Arundel',
    location: 'Glenfield, Auckland',
    category: 'Current Projects',
    statusClass: 'status-construction',
    statusLabel: 'Ongoing',
    cardImage: 'img/46-arundel/Arundel_exterior_1.jpg',
    heroImage: 'img/46-arundel/Arundel_exterior_1.jpg',
    cardDesc: 'A contemporary residential development at 46 Arundel delivering well-designed homes with quality finishes and practical layouts suited to modern living.',
    overviewTitle: '46 Arundel',
    overviewBody: `<p>Situated in the heart of Glenfield on Auckland's North Shore, <strong>46 Arundel</strong> is a contemporary residential development delivering thoughtfully designed homes that balance modern aesthetics with everyday practicality. Each home features quality finishes, open-plan living spaces, and efficient layouts tailored for families and first-home buyers alike. With excellent access to motorways, schools, shopping centres, and public transport, Glenfield offers the perfect blend of suburban comfort and urban connectivity — making 46 Arundel an outstanding opportunity in a well-established North Shore community.</p>`,
    specs: [
      { label: 'Address', value: '46 Arundel' },
      { label: 'Status', value: 'Under Construction' },
    ],
    highlights: [
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
      { title: 'Register Your Interest', body: 'Contact our team to receive updates on this development, including pricing and availability.' },
    ],
    images: [
      'img/46-arundel/Arundel_exterior_1.jpg',
      'img/46-arundel/Arundel_exterior_2.jpg',
      'img/46-arundel/Arundel_exterior_3.jpg',
      'img/46-arundel/Arundel_exterior_4.jpg',
      'img/46-arundel/Arundel_exterior_5.jpg',
      'img/46-arundel/Arundel_exterior_6.jpg',
      'img/46-arundel/6Arundel_interior1.jpg',
      'img/46-arundel/6Arundel_interior2.jpg',
      'img/46-arundel/6Arundel_interior3.jpg',
    ],
    enquireTitle: 'Register Interest — 46 Arundel',
    enquireBody: 'Register your interest to receive updates on this development, including pricing and availability.',
  },
  millen: {
    name: '39 Millen Ave',
    location: 'Auckland',
    category: 'Current Projects',
    statusClass: 'status-completed',
    statusLabel: 'Completed',
    cardImage: 'img/39-millen-ave/08a_EXT.jpg',
    heroImage: 'img/39-millen-ave/08a_EXT.jpg',
    cardDesc: 'A quality residential development at 39 Millen Ave delivering thoughtfully designed homes with contemporary finishes in a well-connected Auckland location.',
    overviewTitle: '39 Millen Ave',
    overviewBody: `<p><strong>39 Millen Ave</strong> is a completed residential development by Krown Properties, delivering a collection of beautifully finished homes in one of Auckland's well-connected suburbs. Each home was designed with modern living in mind — featuring open-plan kitchens, spacious bedrooms, and private outdoor areas. The development showcases Krown Properties' commitment to high-quality construction, clean architectural lines, and thoughtful spatial planning. The successful completion of this project reflects our team's ability to deliver on time and to the highest standard, with all homes now occupied by satisfied residents.</p>`,
    specs: [
      { label: 'Address', value: '39 Millen Ave' },
      { label: 'Status', value: 'Completed' },
    ],
    highlights: [
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
      { title: 'Register Your Interest', body: 'Contact our team to receive updates on this development, including pricing and availability.' },
    ],
    images: [
      'img/39-millen-ave/08a_EXT.jpg',
      'img/39-millen-ave/09a_EXT.jpg',
      'img/39-millen-ave/10_aerial.jpg',
      'img/39-millen-ave/03_KIT.jpg',
      'img/39-millen-ave/04_LIV.jpg',
      'img/39-millen-ave/05_LIV.jpg',
      'img/39-millen-ave/06_KIT.jpg',
      'img/39-millen-ave/07_LIV.jpg',
      'img/39-millen-ave/BED_01.jpg',
      'img/39-millen-ave/BED_02.jpg',
    ],
    enquireTitle: 'Register Interest — 39 Millen Ave',
    enquireBody: 'Register your interest to receive updates on this development, including pricing and availability.',
  },
  wellesley: {
    name: '22 Wellesley, Mangere',
    location: 'Māngere, Auckland',
    category: 'Current Projects',
    statusClass: 'status-construction',
    statusLabel: 'Ongoing',
    cardImage: 'img/22-wellesley-mangere/22WellesleyRoad_exterior1.jpg',
    heroImage: 'img/22-wellesley-mangere/22WellesleyRoad_exterior1.jpg',
    cardDesc: 'A residential development at 22 Wellesley, Mangere, delivering quality homes in a well-connected South Auckland location close to transport and amenities.',
    overviewTitle: '22 Wellesley, Mangere',
    overviewBody: `<p>Located in Māngere, South Auckland, <strong>22 Wellesley</strong> is an ongoing residential development offering quality homes in one of Auckland's most strategically positioned suburbs. Just minutes from Auckland International Airport, State Highway 20, and a range of local schools, shops, and parks, Māngere provides outstanding convenience for working families and investors alike. This development delivers contemporary homes with quality finishes and practical layouts, designed to complement the area's vibrant and diverse community while meeting the growing housing demand in South Auckland.</p>`,
    specs: [
      { label: 'Address', value: '22 Wellesley, Mangere' },
      { label: 'Status', value: 'Under Construction' },
    ],
    highlights: [
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
      { title: 'Register Your Interest', body: 'Contact our team to receive updates on this development, including pricing and availability.' },
    ],
    images: [
      'img/22-wellesley-mangere/22WellesleyRoad_exterior1.jpg',
      'img/22-wellesley-mangere/22WellesleyRoad_exterior2.jpg',
      'img/22-wellesley-mangere/22WellesleyRoad_exterior3.jpg',
      'img/22-wellesley-mangere/22WellesleyRoad_exterior4.jpg',
      'img/22-wellesley-mangere/22WellesleyRoad_exterior5.jpg',
      'img/22-wellesley-mangere/Wellesley_interior1.jpg',
      'img/22-wellesley-mangere/Wellesley_interior2.jpg',
    ],
    enquireTitle: 'Register Interest — 22 Wellesley Mangere',
    enquireBody: 'Register your interest to receive updates on this development, including pricing and availability.',
  },
  sunnyhills: {
    name: '18 Sunnyhills',
    location: 'Sunnyhills, Auckland',
    category: 'Current Projects',
    statusClass: 'status-coming',
    statusLabel: 'Upcoming',
    cardImage: 'img/18-sunnyhills/18SunnyhillCrescent_exterior1.jpg',
    heroImage: 'img/18-sunnyhills/18SunnyhillCrescent_exterior1.jpg',
    cardDesc: 'A contemporary residential development at 18 Sunnyhills offering modern homes with quality finishes in one of Auckland\'s established eastern suburbs.',
    overviewTitle: '18 Sunnyhills',
    overviewBody: `<p>Nestled in Sunnyhills, one of Auckland's most sought-after eastern suburbs, <strong>18 Sunnyhills</strong> is an upcoming development set to deliver a select collection of quality homes in a peaceful, well-established neighbourhood. Sunnyhills is renowned for its excellent school zones, tree-lined streets, and close proximity to Pakuranga, Botany, and key motorway access. This development offers discerning buyers the rare opportunity to secure a brand-new, architecturally considered home in a location that consistently commands strong long-term value.</p>`,
    specs: [
      { label: 'Address', value: '18 Sunnyhills' },
      { label: 'Status', value: 'Upcoming' },
    ],
    highlights: [
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
      { title: 'Register Your Interest', body: 'Contact our team to receive updates on this development, including pricing and availability.' },
    ],
    images: [
      'img/18-sunnyhills/18SunnyhillCrescent_exterior1.jpg',
      'img/18-sunnyhills/18SunnyhillCrescent_exterior2.jpg',
      'img/18-sunnyhills/18SunnyhillCrescent_exterior3.jpg',
      'img/18-sunnyhills/18SunnyhillCrescent_exterior4.jpg',
      'img/18-sunnyhills/18Sunnyhill_interior1.jpg',
      'img/18-sunnyhills/18Sunnyhill_interior2.jpg',
    ],
    enquireTitle: 'Register Interest — 18 Sunnyhills',
    enquireBody: 'Register your interest to receive updates on this development, including pricing and availability.',
  },
  wilbur: {
    name: '15 Wilbur Place',
    location: 'Takanini, Auckland',
    category: 'Current Projects',
    statusClass: 'status-completed',
    statusLabel: 'Completed',
    cardImage: 'img/15-wilbur-place/15WilburPlace_exterior1.jpg',
    heroImage: 'img/15-wilbur-place/15WilburPlace_exterior1.jpg',
    cardDesc: 'A quality residential development at 15 Wilbur Place delivering well-designed homes with contemporary finishes and practical layouts for modern living.',
    overviewTitle: '15 Wilbur Place',
    overviewBody: `<p><strong>15 Wilbur Place</strong> in Takanini, South Auckland, is a successfully completed Krown Properties development offering well-designed homes in a rapidly growing part of the city. Takanini has become one of Auckland's most dynamic growth corridors, benefiting from significant infrastructure investment, new schools, and easy motorway access connecting residents to the wider Auckland region. This development delivered a range of quality homes built to a high standard, with all residences now complete and occupied — a testament to Krown Properties' reliable delivery and commitment to quality craftsmanship.</p>`,
    specs: [
      { label: 'Address', value: '15 Wilbur Place' },
      { label: 'Status', value: 'Completed' },
    ],
    highlights: [
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
      { title: 'Register Your Interest', body: 'Contact our team to receive updates on this development, including pricing and availability.' },
    ],
    images: [
      'img/15-wilbur-place/15WilburPlace_exterior1.jpg',
      'img/15-wilbur-place/15WilburPlace_exterior2.jpg',
      'img/15-wilbur-place/15WilburPlace_exterior3.jpg',
      'img/15-wilbur-place/15WilburPlace_exterior4.jpg',
      'img/15-wilbur-place/15WilburPlace_interior1.jpg',
      'img/15-wilbur-place/15WilburPlace_interior2.jpg',
      'img/15-wilbur-place/15WilburPlace_interior3.jpg',
      'img/15-wilbur-place/15WilburPlace_interior4.jpg',
    ],
    enquireTitle: 'Register Interest — 15 Wilbur Place',
    enquireBody: 'Register your interest to receive updates on this development, including pricing and availability.',
  },
  taylor: {
    name: '86 Taylor Street',
    location: 'Papakura, Auckland',
    category: 'Current Projects',
    statusClass: 'status-coming',
    statusLabel: 'Upcoming',
    cardImage: 'img/86-taylor-street/1.jpg',
    heroImage: 'img/86-taylor-street/1.jpg',
    cardDesc: 'A modern residential development at 86 Taylor Street delivering quality homes with thoughtful design and high-standard finishes in an Auckland location.',
    overviewTitle: '86 Taylor Street',
    overviewBody: `<p>Located in Papakura, South Auckland, <strong>86 Taylor Street</strong> is an upcoming residential development bringing quality new homes to one of the region's fastest-growing communities. Papakura offers outstanding connectivity via the Southern Motorway and rail network, making it an ideal base for families and commuters. This development will deliver a collection of modern homes featuring generous living spaces, contemporary kitchen and bathroom finishes, and private outdoor areas — all within easy reach of Papakura town centre, schools, and recreational facilities. Register your interest early to secure priority access.</p>`,
    specs: [
      { label: 'Address', value: '86 Taylor Street' },
      { label: 'Status', value: 'Under Construction' },
    ],
    highlights: [
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
      { title: 'Register Your Interest', body: 'Contact our team to receive updates on this development, including pricing and availability.' },
    ],
    images: [
      'img/86-taylor-street/1.jpg',
    ],
    enquireTitle: 'Register Interest — 86 Taylor Street',
    enquireBody: 'Register your interest to receive updates on this development, including pricing and availability.',
  },
  mountain: {
    name: '100 Mountain Road',
    location: 'Epsom, Auckland',
    category: 'Current Projects',
    statusClass: 'status-coming',
    statusLabel: 'Upcoming',
    cardImage: 'img/100-mountain-road/1.jpg',
    heroImage: 'img/100-mountain-road/1.jpg',
    cardDesc: 'A prestigious residential development at 100 Mountain Road in Epsom delivering architecturally considered homes in one of Auckland\'s most sought-after suburbs.',
    overviewTitle: '100 Mountain Road',
    overviewBody: `<p>Set in the prestigious suburb of Epsom, central Auckland, <strong>100 Mountain Road</strong> represents a rare opportunity to secure a new-build home in one of the city's most coveted addresses. Epsom is celebrated for its top-performing school zones, leafy streets, and proximity to the CBD, Newmarket, and Royal Oak. This upcoming development will deliver a limited collection of architecturally considered residences featuring premium finishes, generous proportions, and refined design details — crafted for buyers who demand the very best. With exceptional long-term capital growth fundamentals, 100 Mountain Road is an investment in both lifestyle and legacy.</p>`,
    specs: [
      { label: 'Address', value: '100 Mountain Road' },
      { label: 'Status', value: 'Upcoming' },
    ],
    highlights: [
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
      { title: 'Register Your Interest', body: 'Contact our team to receive updates on this development, including pricing and availability.' },
    ],
    images: [
      'img/100-mountain-road/1.jpg',
    ],
    enquireTitle: 'Register Interest — 100 Mountain Road',
    enquireBody: 'Register your interest to receive updates on this development, including pricing and availability.',
  },
};
