// Krown Properties — Project Data
// Images are now loaded from /img folder

var PROJECTS = {
  arundel: {
    name: '46 Arundel',
    location: 'Glenfield, Auckland',
    category: 'Current Projects',
    statusClass: 'status-construction',
    statusLabel: 'Ongoing',
    units: 6, beds: '3–4', baths: 2,
    cardImage: 'img/46-arundel/Arundel_exterior_1.jpg',
    heroImage: 'img/46-arundel/Arundel_exterior_1.jpg',
    cardDesc: 'A contemporary residential development at 46 Arundel delivering well-designed homes with quality finishes and practical layouts suited to modern living.',
    overviewTitle: '46 Arundel',
    overviewBody: `<p>Situated in the heart of Glenfield on Auckland's North Shore, <strong>46 Arundel</strong> is a contemporary residential development delivering thoughtfully designed homes that balance modern aesthetics with everyday practicality. Each home features quality finishes, open-plan living spaces, and efficient layouts tailored for families and first-home buyers alike. With excellent access to motorways, schools, shopping centres, and public transport, Glenfield offers the perfect blend of suburban comfort and urban connectivity — making 46 Arundel an outstanding opportunity in a well-established North Shore community.</p>`,
    specs: [
      { label: 'Address', value: '46 Arundel' },
      { label: 'Status', value: 'Under Construction' },
    ],
    highlights: [
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
      { title: 'Register Your Interest', body: 'Contact our team to receive updates on this development, including pricing and availability.' },
    ],
    images: [
      'img/46-arundel/Arundel_exterior_1.jpg',
      'img/46-arundel/Arundel_exterior_2.jpg',
      'img/46-arundel/Arundel_exterior_3.jpg',
      'img/46-arundel/Arundel_exterior_4.jpg',
      'img/46-arundel/Arundel_exterior_5.jpg',
      'img/46-arundel/Arundel_exterior_6.jpg',
      'img/46-arundel/6Arundel_interior1.jpg',
      'img/46-arundel/6Arundel_interior2.jpg',
      'img/46-arundel/6Arundel_interior3.jpg',
    ],
    enquireTitle: 'Register Interest — 46 Arundel',
    enquireBody: 'Register your interest to receive updates on this development, including pricing and availability.',
  },
  millen: {
    name: '39 Millen Ave',
    location: 'Auckland',
    category: 'Current Projects',
    statusClass: 'status-completed',
    statusLabel: 'Completed',
    units: 5, beds: 3, baths: 2,
    cardImage: 'img/39-millen-ave/08a_EXT.jpg',
    heroImage: 'img/39-millen-ave/08a_EXT.jpg',
    cardDesc: 'A quality residential development at 39 Millen Ave delivering thoughtfully designed homes with contemporary finishes in a well-connected Auckland location.',
    overviewTitle: '39 Millen Ave',
    overviewBody: `<p><strong>39 Millen Ave</strong> is a completed residential development by Krown Properties, delivering a collection of beautifully finished homes in one of Auckland's well-connected suburbs. Each home was designed with modern living in mind — featuring open-plan kitchens, spacious bedrooms, and private outdoor areas. The development showcases Krown Properties' commitment to high-quality construction, clean architectural lines, and thoughtful spatial planning. The successful completion of this project reflects our team's ability to deliver on time and to the highest standard, with all homes now occupied by satisfied residents.</p>`,
    specs: [
      { label: 'Address', value: '39 Millen Ave' },
      { label: 'Status', value: 'Completed' },
    ],
    highlights: [
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
      { title: 'Register Your Interest', body: 'Contact our team to receive updates on this development, including pricing and availability.' },
    ],
    images: [
      'img/39-millen-ave/08a_EXT.jpg',
      'img/39-millen-ave/09a_EXT.jpg',
      'img/39-millen-ave/10_aerial.jpg',
      'img/39-millen-ave/03_KIT.jpg',
      'img/39-millen-ave/04_LIV.jpg',
      'img/39-millen-ave/05_LIV.jpg',
      'img/39-millen-ave/06_KIT.jpg',
      'img/39-millen-ave/07_LIV.jpg',
      'img/39-millen-ave/BED_01.jpg',
      'img/39-millen-ave/BED_02.jpg',
    ],
    enquireTitle: 'Register Interest — 39 Millen Ave',
    enquireBody: 'Register your interest to receive updates on this development, including pricing and availability.',
  },
  wellesley: {
    name: '22 Wellesley, Mangere',
    location: 'Māngere, Auckland',
    category: 'Current Projects',
    statusClass: 'status-construction',
    statusLabel: 'Ongoing',
    units: 8, beds: '3–4', baths: 2,
    cardImage: 'img/22-wellesley-mangere/22WellesleyRoad_exterior1.jpg',
    heroImage: 'img/22-wellesley-mangere/22WellesleyRoad_exterior1.jpg',
    cardDesc: 'A residential development at 22 Wellesley, Mangere, delivering quality homes in a well-connected South Auckland location close to transport and amenities.',
    overviewTitle: '22 Wellesley, Mangere',
    overviewBody: `<p>Located in Māngere, South Auckland, <strong>22 Wellesley</strong> is an ongoing residential development offering quality homes in one of Auckland's most strategically positioned suburbs. Just minutes from Auckland International Airport, State Highway 20, and a range of local schools, shops, and parks, Māngere provides outstanding convenience for working families and investors alike. This development delivers contemporary homes with quality finishes and practical layouts, designed to complement the area's vibrant and diverse community while meeting the growing housing demand in South Auckland.</p>`,
    specs: [
      { label: 'Address', value: '22 Wellesley, Mangere' },
      { label: 'Status', value: 'Under Construction' },
    ],
    highlights: [
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
      { title: 'Register Your Interest', body: 'Contact our team to receive updates on this development, including pricing and availability.' },
    ],
    images: [
      'img/22-wellesley-mangere/22WellesleyRoad_exterior1.jpg',
      'img/22-wellesley-mangere/22WellesleyRoad_exterior2.jpg',
      'img/22-wellesley-mangere/22WellesleyRoad_exterior3.jpg',
      'img/22-wellesley-mangere/22WellesleyRoad_exterior4.jpg',
      'img/22-wellesley-mangere/22WellesleyRoad_exterior5.jpg',
      'img/22-wellesley-mangere/Wellesley_interior1.jpg',
      'img/22-wellesley-mangere/Wellesley_interior2.jpg',
    ],
    enquireTitle: 'Register Interest — 22 Wellesley Mangere',
    enquireBody: 'Register your interest to receive updates on this development, including pricing and availability.',
  },
  sunnyhills: {
    name: '18 Sunnyhills',
    location: 'Sunnyhills, Auckland',
    category: 'Current Projects',
    statusClass: 'status-coming',
    statusLabel: 'Upcoming',
    units: 4, beds: 4, baths: 2,
    cardImage: 'img/18-sunnyhills/18SunnyhillCrescent_exterior1.jpg',
    heroImage: 'img/18-sunnyhills/18SunnyhillCrescent_exterior1.jpg',
    cardDesc: 'A contemporary residential development at 18 Sunnyhills offering modern homes with quality finishes in one of Auckland\'s established eastern suburbs.',
    overviewTitle: '18 Sunnyhills',
    overviewBody: `<p>Nestled in Sunnyhills, one of Auckland's most sought-after eastern suburbs, <strong>18 Sunnyhills</strong> is an upcoming development set to deliver a select collection of quality homes in a peaceful, well-established neighbourhood. Sunnyhills is renowned for its excellent school zones, tree-lined streets, and close proximity to Pakuranga, Botany, and key motorway access. This development offers discerning buyers the rare opportunity to secure a brand-new, architecturally considered home in a location that consistently commands strong long-term value.</p>`,
    specs: [
      { label: 'Address', value: '18 Sunnyhills' },
      { label: 'Status', value: 'Upcoming' },
    ],
    highlights: [
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
      { title: 'Register Your Interest', body: 'Contact our team to receive updates on this development, including pricing and availability.' },
    ],
    images: [
      'img/18-sunnyhills/18SunnyhillCrescent_exterior1.jpg',
      'img/18-sunnyhills/18SunnyhillCrescent_exterior2.jpg',
      'img/18-sunnyhills/18SunnyhillCrescent_exterior3.jpg',
      'img/18-sunnyhills/18SunnyhillCrescent_exterior4.jpg',
      'img/18-sunnyhills/18Sunnyhill_interior1.jpg',
      'img/18-sunnyhills/18Sunnyhill_interior2.jpg',
    ],
    enquireTitle: 'Register Interest — 18 Sunnyhills',
    enquireBody: 'Register your interest to receive updates on this development, including pricing and availability.',
  },
  wilbur: {
    name: '15 Wilbur Place',
    location: 'Takanini, Auckland',
    category: 'Current Projects',
    statusClass: 'status-completed',
    statusLabel: 'Completed',
    units: 7, beds: 3, baths: 2,
    cardImage: 'img/15-wilbur-place/15WilburPlace_exterior1.jpg',
    heroImage: 'img/15-wilbur-place/15WilburPlace_exterior1.jpg',
    cardDesc: 'A quality residential development at 15 Wilbur Place delivering well-designed homes with contemporary finishes and practical layouts for modern living.',
    overviewTitle: '15 Wilbur Place',
    overviewBody: `<p><strong>15 Wilbur Place</strong> in Takanini, South Auckland, is a successfully completed Krown Properties development offering well-designed homes in a rapidly growing part of the city. Takanini has become one of Auckland's most dynamic growth corridors, benefiting from significant infrastructure investment, new schools, and easy motorway access connecting residents to the wider Auckland region. This development delivered a range of quality homes built to a high standard, with all residences now complete and occupied — a testament to Krown Properties' reliable delivery and commitment to quality craftsmanship.</p>`,
    specs: [
      { label: 'Address', value: '15 Wilbur Place' },
      { label: 'Status', value: 'Completed' },
    ],
    highlights: [
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
      { title: 'Register Your Interest', body: 'Contact our team to receive updates on this development, including pricing and availability.' },
    ],
    images: [
      'img/15-wilbur-place/15WilburPlace_exterior1.jpg',
      'img/15-wilbur-place/15WilburPlace_exterior2.jpg',
      'img/15-wilbur-place/15WilburPlace_exterior3.jpg',
      'img/15-wilbur-place/15WilburPlace_exterior4.jpg',
      'img/15-wilbur-place/15WilburPlace_interior1.jpg',
      'img/15-wilbur-place/15WilburPlace_interior2.jpg',
      'img/15-wilbur-place/15WilburPlace_interior3.jpg',
      'img/15-wilbur-place/15WilburPlace_interior4.jpg',
    ],
    enquireTitle: 'Register Interest — 15 Wilbur Place',
    enquireBody: 'Register your interest to receive updates on this development, including pricing and availability.',
  },
  taylor: {
    name: '86 Taylor Street',
    location: 'Papakura, Auckland',
    category: 'Current Projects',
    statusClass: 'status-coming',
    statusLabel: 'Upcoming',
    units: 5, beds: '3–4', baths: 2,
    cardImage: 'img/86-taylor-street/86TaylorStreet_exterior1.jpg',
    heroImage: 'img/86-taylor-street/86TaylorStreet_exterior1.jpg',
    cardDesc: 'A modern residential development at 86 Taylor Street delivering quality homes with thoughtful design and high-standard finishes in an Auckland location.',
    overviewTitle: '86 Taylor Street',
    overviewBody: `<p>Located in Papakura, South Auckland, <strong>86 Taylor Street</strong> is an upcoming residential development bringing quality new homes to one of the region's fastest-growing communities. Papakura offers outstanding connectivity via the Southern Motorway and rail network, making it an ideal base for families and commuters. This development will deliver a collection of modern homes featuring generous living spaces, contemporary kitchen and bathroom finishes, and private outdoor areas — all within easy reach of Papakura town centre, schools, and recreational facilities. Register your interest early to secure priority access.</p>`,
    specs: [
      { label: 'Address', value: '86 Taylor Street' },
      { label: 'Status', value: 'Under Construction' },
    ],
    highlights: [
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
      { title: 'Register Your Interest', body: 'Contact our team to receive updates on this development, including pricing and availability.' },
    ],
    images: [
      'img/86-taylor-street/86TaylorStreet_exterior1.jpg',
      'img/86-taylor-street/86TaylorStreet_exterior2.jpg',
      'img/86-taylor-street/86TaylorStreet_exterior3.jpg',
      'img/86-taylor-street/86TaylorStreet_exterior4.jpg',
      'img/86-taylor-street/86TaylorStreet_exterior5.jpg',
      'img/86-taylor-street/86TaylorStreet_exterior6.jpg',
      'img/86-taylor-street/86TaylorStreet_exterior7.jpg',
      'img/86-taylor-street/86TaylorStreet_exterior8.jpg',
      'img/86-taylor-street/86TaylorStreet_exterior9.jpg',
    ],
    enquireTitle: 'Register Interest — 86 Taylor Street',
    enquireBody: 'Register your interest to receive updates on this development, including pricing and availability.',
  },
  walworth: {
    name: '69 Walworth Avenue',
    location: 'Pakuranga, Auckland',
    category: 'Homes for Sale',
    statusClass: 'status-construction',
    statusLabel: 'For Sale',
    units: 4, beds: 3, baths: 2,
    cardImage: 'https://reliancehomes.co.nz/wp-content/uploads/2025/05/front-1-2.jpg',
    heroImage: 'https://reliancehomes.co.nz/wp-content/uploads/2025/05/front-1-2.jpg',
    cardDesc: 'A quality new build at 69 Walworth Avenue, Pakuranga — offering well-designed homes with modern finishes in a well-connected East Auckland location.',
    overviewTitle: '69 Walworth Avenue, Pakuranga',
    overviewBody: `<p><strong>69 Walworth Avenue</strong> is a new residential development in Pakuranga, East Auckland — one of the region's most sought-after suburban locations. Close to shopping centres, motorway access, and quality schools, these homes offer contemporary design, quality materials, and practical layouts suited to families and investors alike.</p>`,
    specs: [
      { label: 'Address', value: '69 Walworth Avenue, Pakuranga' },
      { label: 'Status', value: 'For Sale' },
    ],
    highlights: [
      { title: 'East Auckland Location', body: 'Pakuranga offers outstanding connectivity to Botany, the CBD, and the wider motorway network.' },
      { title: 'Enquire Today', body: 'Contact our team to find out more about pricing, availability, and viewing times.' },
    ],
    images: [
      'https://reliancehomes.co.nz/wp-content/uploads/2025/05/front-1-2.jpg',
    ],
    enquireTitle: 'Enquire — 69 Walworth Avenue',
    enquireBody: 'Contact our team to find out more about this property including pricing and availability.',
  },
  walmsley: {
    name: '22 Walmsley Road',
    location: 'Māngere, Auckland',
    category: 'Homes for Sale',
    statusClass: 'status-construction',
    statusLabel: 'For Sale',
    units: 4, beds: 3, baths: 2,
    cardImage: 'img/22-walmsley-road/DJI_20250908174217_0815_D-Recovered.jpg',
    heroImage: 'img/22-walmsley-road/DJI_20250908174217_0815_D-Recovered.jpg',
    cardDesc: 'Quality new homes at 22 Walmsley Road, Māngere — a well-connected South Auckland location close to Auckland Airport, motorways, and local amenities.',
    overviewTitle: '22 Walmsley Road, Māngere',
    overviewBody: `<p><strong>22 Walmsley Road</strong> is a new residential development in Māngere, South Auckland. Strategically positioned near Auckland International Airport and State Highway 20, Māngere is one of the city's most accessible suburbs. These homes offer modern design and quality construction in a vibrant, diverse community.</p>`,
    specs: [
      { label: 'Address', value: '22 Walmsley Road, Māngere' },
      { label: 'Status', value: 'For Sale' },
    ],
    highlights: [
      { title: 'South Auckland Connectivity', body: 'Easy access to Auckland Airport, SH20, and the wider motorway network makes this an ideal location for commuters.' },
      { title: 'Enquire Today', body: 'Contact our team to find out more about pricing, availability, and viewing times.' },
    ],
    images: [
      'img/22-walmsley-road/DJI_20250908174217_0815_D-Recovered.jpg',
      'img/22-walmsley-road/DJI_20250908174250_0816_D.jpg',
      'img/22-walmsley-road/DSC08977-DSC08981.jpg',
      'img/22-walmsley-road/DSC08992-DSC08996.jpg',
      'img/22-walmsley-road/DSC09007-DSC09011.jpg',
      'img/22-walmsley-road/DSC09012-DSC09016.jpg',
      'img/22-walmsley-road/DSC09022-DSC09026.jpg',
      'img/22-walmsley-road/DSC09037-DSC09041.jpg',
      'img/22-walmsley-road/DSC09042-DSC09046.jpg',
      'img/22-walmsley-road/DSC09057-DSC09061.jpg',
      'img/22-walmsley-road/DSC09067.jpg',
      'img/22-walmsley-road/DSC09082-DSC09086.jpg',
      'img/22-walmsley-road/DSC09092-DSC09096.jpg',
      'img/22-walmsley-road/DSC09102-DSC09106.jpg',
      'img/22-walmsley-road/DSC09107-DSC09111.jpg',
    ],
    enquireTitle: 'Enquire — 22 Walmsley Road',
    enquireBody: 'Contact our team to find out more about this property including pricing and availability.',
  },
  kurnell: {
    name: '13 Kurnell Drive',
    location: 'Botany Downs, Auckland',
    category: 'Homes for Sale',
    statusClass: 'status-construction',
    statusLabel: 'For Sale',
    units: 4, beds: 3, baths: 2,
    cardImage: 'img/13-kurnell-drive/0T5A9149.jpg',
    heroImage: 'img/13-kurnell-drive/0T5A9149.jpg',
    cardDesc: 'Premium new homes at 13 Kurnell Drive, Botany Downs — quality construction in one of East Auckland\'s most desirable and well-established suburbs.',
    overviewTitle: '13 Kurnell Drive, Botany Downs',
    overviewBody: `<p><strong>13 Kurnell Drive</strong> is a new residential development in Botany Downs, one of East Auckland's most premium suburban addresses. With outstanding school zones, the Botany Town Centre, and excellent motorway access all nearby, this development delivers exceptional lifestyle value. Each home features quality finishes and contemporary design in a location that consistently ranks among Auckland's most sought-after.</p>`,
    specs: [
      { label: 'Address', value: '13 Kurnell Drive, Botany Downs' },
      { label: 'Status', value: 'For Sale' },
    ],
    highlights: [
      { title: 'Premium Location', body: 'Botany Downs is recognised for its top school zones, retail amenities, and strong long-term property values.' },
      { title: 'Enquire Today', body: 'Contact our team to find out more about pricing, availability, and viewing times.' },
    ],
    images: [
      'img/13-kurnell-drive/0T5A9149.jpg',
      'img/13-kurnell-drive/0T5A9158.jpg',
      'img/13-kurnell-drive/0T5A9170.jpg',
      'img/13-kurnell-drive/0T5A9191.jpg',
      'img/13-kurnell-drive/0T5A9197.jpg',
      'img/13-kurnell-drive/0T5A9300.jpg',
      'img/13-kurnell-drive/0T5A9306 copy.jpg',
      'img/13-kurnell-drive/0T5A9312.jpg',
      'img/13-kurnell-drive/0T5A9315 copy.jpg',
      'img/13-kurnell-drive/0T5A9321.jpg',
      'img/13-kurnell-drive/DJI_20250828180940_0840_D copy.jpg',
    ],
    enquireTitle: 'Enquire — 13 Kurnell Drive',
    enquireBody: 'Contact our team to find out more about this property including pricing and availability.',
  },
  angelo: {
    name: '41 Angelo Avenue',
    location: 'Howick, Auckland',
    category: 'Homes for Sale',
    statusClass: 'status-construction',
    statusLabel: 'For Sale',
    units: 4, beds: 3, baths: 2,
    cardImage: 'img/41-angelo-avenue/FXPH0303.jpg',
    heroImage: 'img/41-angelo-avenue/FXPH0303.jpg',
    cardDesc: 'Quality new homes at 41 Angelo Avenue, Howick — a sought-after East Auckland coastal suburb offering excellent schools, amenities, and village character.',
    overviewTitle: '41 Angelo Avenue, Howick',
    overviewBody: `<p><strong>41 Angelo Avenue</strong> is a new residential development in Howick, a charming coastal suburb on Auckland's East Coast Bays. Known for its village atmosphere, award-winning schools, and proximity to beautiful beaches, Howick is consistently one of Auckland's most desirable addresses. These homes offer thoughtful design and quality craftsmanship in a location that families love.</p>`,
    specs: [
      { label: 'Address', value: '41 Angelo Avenue, Howick' },
      { label: 'Status', value: 'For Sale' },
    ],
    highlights: [
      { title: 'Howick Village', body: 'Steps from cafes, boutique shops, and the beach — Howick offers a lifestyle that is hard to match anywhere in Auckland.' },
      { title: 'Enquire Today', body: 'Contact our team to find out more about pricing, availability, and viewing times.' },
    ],
    images: [
      'img/41-angelo-avenue/FXPH0303.jpg',
      'img/41-angelo-avenue/FXPH0310.jpg',
      'img/41-angelo-avenue/FXPH0331.jpg',
      'img/41-angelo-avenue/FXPH0359.jpg',
      'img/41-angelo-avenue/FXPH040.jpg',
      'img/41-angelo-avenue/FXPH0429.jpg',
      'img/41-angelo-avenue/FXPH0443.jpg',
      'img/41-angelo-avenue/FXPH0450.jpg',
      'img/41-angelo-avenue/DJI_0932.jpg',
      'img/41-angelo-avenue/DJI_09347.jpg',
      'img/41-angelo-avenue/DJI_0997.jpg',
    ],
    enquireTitle: 'Enquire — 41 Angelo Avenue',
    enquireBody: 'Contact our team to find out more about this property including pricing and availability.',
  },
  broadview6: {
    name: '6 Broadview Place',
    location: 'Howick, Auckland',
    category: 'Homes for Sale',
    statusClass: 'status-construction',
    statusLabel: 'For Sale',
    units: 3, beds: 3, baths: 2,
    cardImage: 'img/7-9-broadview-place/6BroadviewPlace_exterior1.jpg',
    heroImage: 'img/7-9-broadview-place/6BroadviewPlace_exterior1.jpg',
    cardDesc: 'New homes at 6 Broadview Place, Howick — quality residential development in a quiet cul-de-sac setting in one of Auckland\'s most loved eastern suburbs.',
    overviewTitle: '6 Broadview Place, Howick',
    overviewBody: `<p><strong>6 Broadview Place</strong> is a new residential development situated in a quiet cul-de-sac in Howick, East Auckland. This beautifully positioned development offers modern homes with quality finishes in a peaceful setting, with easy access to Howick's village, top schools, and stunning coastal walks.</p>`,
    specs: [
      { label: 'Address', value: '6 Broadview Place, Howick' },
      { label: 'Status', value: 'For Sale' },
    ],
    highlights: [
      { title: 'Quiet Cul-de-Sac Setting', body: 'A private and peaceful location within easy reach of all the amenities Howick has to offer.' },
      { title: 'Enquire Today', body: 'Contact our team to find out more about pricing, availability, and viewing times.' },
    ],
    images: [
      'img/7-9-broadview-place/6BroadviewPlace_exterior1.jpg',
      'img/7-9-broadview-place/6BroadviewPlace_exterior2.jpg',
      'img/7-9-broadview-place/6BroadviewPlace_exterior3.jpg',
      'img/7-9-broadview-place/6BroadviewPlace_exterior4.jpg',
      'img/7-9-broadview-place/6BroadviewPlace_exterior5.jpg',
      'img/7-9-broadview-place/6BroadviewPlace_exterior6.jpg',
      'img/7-9-broadview-place/6%20Broadview%20Place_exterior2.jpg',
      'img/7-9-broadview-place/6%20Broadview%20Place_interior1.jpg',
    ],
    enquireTitle: 'Enquire — 6 Broadview Place',
    enquireBody: 'Contact our team to find out more about this property including pricing and availability.',
  },
  rosina: {
    name: '6 Rosina Place',
    location: 'Pakuranga Heights, Auckland',
    category: 'Homes for Sale',
    statusClass: 'status-coming',
    statusLabel: 'Upcoming',
    units: 4, beds: 3, baths: 2,
    cardImage: 'img/6-rosina-place/Rosina6Place_exterior1.jpg',
    heroImage: 'img/6-rosina-place/Rosina6Place_exterior1.jpg',
    cardDesc: 'An upcoming residential development at 6 Rosina Place, Pakuranga Heights — quality new homes in a sought-after elevated position in East Auckland.',
    overviewTitle: '6 Rosina Place, Pakuranga Heights',
    overviewBody: `<p><strong>6 Rosina Place</strong> is an upcoming residential development in Pakuranga Heights, one of East Auckland's most elevated and desirable residential pockets. Offering sweeping views and excellent connectivity to Pakuranga Town Centre, motorways, and top schools, this development represents a rare opportunity to secure a quality new home in a premium location.</p>`,
    specs: [
      { label: 'Address', value: '6 Rosina Place, Pakuranga Heights' },
      { label: 'Status', value: 'Upcoming' },
    ],
    highlights: [
      { title: 'Elevated East Auckland Position', body: 'Pakuranga Heights offers elevated living with outstanding access to East Auckland\'s amenities and motorway network.' },
      { title: 'Register Your Interest', body: 'Contact our team to register your interest and receive updates on this upcoming development.' },
    ],
    images: [
      'img/6-rosina-place/Rosina6Place_exterior1.jpg',
      'img/6-rosina-place/Rosina6Place_exterior2.jpg',
      'img/6-rosina-place/Rosina6Place_exterior3.jpg',
      'img/6-rosina-place/Rosina%206%20Place_exterior4.jpg',
      'img/6-rosina-place/Rosina%206%20Place_exterior5.jpg',
      'img/6-rosina-place/Rosina_interior1.jpg',
      'img/6-rosina-place/Rosina_interior2.jpg',
    ],
    enquireTitle: 'Register Interest — 6 Rosina Place',
    enquireBody: 'Register your interest to receive updates on this upcoming development, including pricing and availability.',
  },
  osprey: {
    name: '4 Osprey Street',
    location: 'Pakuranga, Auckland',
    category: 'Completed Homes',
    statusClass: 'status-completed',
    statusLabel: 'Completed',
    cardImage: 'img/4-osprey-street/DJI_0814.jpg',
    heroImage: 'img/4-osprey-street/DJI_0814.jpg',
    cardDesc: 'A quality completed residential development at 4 Osprey Street, Pakuranga, delivering well-designed homes with contemporary finishes in a sought-after Auckland location.',
    overviewTitle: '4 Osprey Street, Pakuranga',
    overviewBody: `<p><strong>4 Osprey Street</strong> in Pakuranga is a completed residential development delivering a collection of quality homes in one of Auckland's most well-connected eastern suburbs. Pakuranga offers excellent motorway access, established schools, and proximity to Botany and Howick town centres. This project reflects Krown Properties' commitment to high-quality construction and thoughtful design — with all homes now occupied by satisfied residents.</p>`,
    specs: [
      { label: 'Address', value: '4 Osprey Street, Pakuranga' },
      { label: 'Status', value: 'Completed' },
    ],
    highlights: [
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
      { title: 'Prime Location', body: 'Situated in Pakuranga, offering outstanding motorway access and proximity to local schools, parks, and shopping.' },
    ],
    images: [
      'img/4-osprey-street/DJI_0814.jpg',
      'img/4-osprey-street/DJI_0818.jpg',
      'img/4-osprey-street/0T5A6700.jpg',
      'img/4-osprey-street/0T5A6703.jpg',
      'img/4-osprey-street/0T5A6706.jpg',
      'img/4-osprey-street/0T5A6721.jpg',
      'img/4-osprey-street/0T5A6724.jpg',
      'img/4-osprey-street/0T5A6730.jpg',
      'img/4-osprey-street/0T5A6745.jpg',
      'img/4-osprey-street/0T5A6754.jpg',
      'img/4-osprey-street/0T5A6757.jpg',
    ],
    enquireTitle: 'Get In Touch — 4 Osprey Street',
    enquireBody: 'This development is now complete. Contact our team to learn more about future projects in this area.',
  },
  seymour: {
    name: '8 Seymour Avenue',
    location: 'Papatoetoe, Auckland',
    category: 'Completed Homes',
    statusClass: 'status-completed',
    statusLabel: 'Completed',
    cardImage: 'img/8-seymour-avenue/8Seymouravenue1.jpeg',
    heroImage: 'img/8-seymour-avenue/8Seymouravenue1.jpeg',
    cardDesc: 'A completed residential development at 8 Seymour Avenue, Papatoetoe, offering modern homes with quality finishes in a well-connected South Auckland community.',
    overviewTitle: '8 Seymour Avenue, Papatoetoe',
    overviewBody: `<p><strong>8 Seymour Avenue</strong> is a completed development in Papatoetoe, South Auckland — one of the region's most strategically connected suburbs. With easy access to State Highway 1, Manukau City Centre, and Auckland Airport, this development delivered a collection of quality homes tailored for families and investors. All residences have been successfully completed and are now occupied.</p>`,
    specs: [
      { label: 'Address', value: '8 Seymour Avenue, Papatoetoe' },
      { label: 'Status', value: 'Completed' },
    ],
    highlights: [
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
      { title: 'Connected Location', body: 'Excellent access to SH1, Manukau, and Auckland Airport — ideal for families and investors.' },
    ],
    images: [
      'img/8-seymour-avenue/8Seymouravenue1.jpeg',
      'img/8-seymour-avenue/8Seymouravenue2.JPEG',
      'img/8-seymour-avenue/8Seymouravenue3.jpeg',
      'img/8-seymour-avenue/8Seymouravenue4.jpeg',
      'img/8-seymour-avenue/8Seymouravenue5.jpeg',
      'img/8-seymour-avenue/8Seymouravenue6.jpeg',
      'img/8-seymour-avenue/8Seymouravenue7.jpeg',
      'img/8-seymour-avenue/8Seymouravenue8.jpeg',
      'img/8-seymour-avenue/8Seymouravenue9.jpeg',
      'img/8-seymour-avenue/8Seymouravenue10.jpeg',
    ],
    enquireTitle: 'Get In Touch — 8 Seymour Avenue',
    enquireBody: 'This development is now complete. Contact our team to learn more about future projects in this area.',
  },
  mclean: {
    name: '11 Mclean Ave',
    location: 'Papatoetoe, Auckland',
    category: 'Completed Homes',
    statusClass: 'status-completed',
    statusLabel: 'Completed',
    cardImage: 'img/11-mclean-ave/002.jpg',
    heroImage: 'img/11-mclean-ave/002.jpg',
    cardDesc: 'A quality completed development at 11 Mclean Ave, Papatoetoe, delivering well-designed homes with modern finishes in a well-connected South Auckland location.',
    overviewTitle: '11 Mclean Ave, Papatoetoe',
    overviewBody: `<p><strong>11 Mclean Ave</strong> is a successfully completed residential development in Papatoetoe, South Auckland. The project delivered a select range of quality homes featuring contemporary interiors, open-plan layouts, and private outdoor areas. The development stands as a demonstration of Krown Properties' ability to deliver high-quality housing in high-demand growth corridors across Auckland.</p>`,
    specs: [
      { label: 'Address', value: '11 Mclean Ave, Papatoetoe' },
      { label: 'Status', value: 'Completed' },
    ],
    highlights: [
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
      { title: 'Modern Design', body: 'Contemporary homes with open-plan living, quality kitchen finishes, and private outdoor areas.' },
    ],
    images: [
      'img/11-mclean-ave/002.jpg',
      'img/11-mclean-ave/2.jpg',
      'img/11-mclean-ave/3..jpg',
      'img/11-mclean-ave/4.jpg',
      'img/11-mclean-ave/bedroom-smallsize.jpg',
      'img/11-mclean-ave/living-smallsize.jpg',
      'img/11-mclean-ave/yard-smallsize.jpg',
    ],
    enquireTitle: 'Get In Touch — 11 Mclean Ave',
    enquireBody: 'This development is now complete. Contact our team to learn more about future projects in this area.',
  },
  broadview: {
    name: '7 & 9 Broadview Place',
    location: 'Howick, Auckland',
    category: 'Completed Homes',
    statusClass: 'status-completed',
    statusLabel: 'Completed',
    cardImage: 'img/6-broadview-place/homepageHOWICK.jpg',
    heroImage: 'img/6-broadview-place/homepageHOWICK.jpg',
    cardDesc: 'A completed residential development at 7 & 9 Broadview Place, Howick, delivering quality homes in one of Auckland\'s most established and sought-after eastern suburbs.',
    overviewTitle: '7 & 9 Broadview Place, Howick',
    overviewBody: `<p><strong>7 & 9 Broadview Place</strong> is a completed dual-site residential development in Howick, one of Auckland's most desirable eastern suburbs. Known for its top-performing schools, village atmosphere, and coastal lifestyle, Howick provides exceptional long-term value. This project delivered quality homes that blend seamlessly into the established neighbourhood character while delivering modern living standards.</p>`,
    specs: [
      { label: 'Address', value: '7 & 9 Broadview Place, Howick' },
      { label: 'Status', value: 'Completed' },
    ],
    highlights: [
      { title: 'Prestigious Location', body: 'Situated in Howick — renowned for top schools, village charm, and easy access to the Manukau Harbour.' },
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
    ],
    images: [
      'img/6-broadview-place/homepageHOWICK.jpg',
      'img/6-broadview-place/homepageHOWICK2.jpg',
      'img/6-broadview-place/homepageHOWICK3.jpeg',
      'img/6-broadview-place/homepageHOWICK4.jpeg',
      'img/6-broadview-place/homepageHOWICK5.jpeg',
      'img/6-broadview-place/homepageHOWICK6.jpeg',
      'img/6-broadview-place/homepageHOWICK7.jpeg',
      'img/6-broadview-place/residentialhomes.jpeg',
    ],
    enquireTitle: 'Get In Touch — 7 & 9 Broadview Place',
    enquireBody: 'This development is now complete. Contact our team to learn more about future projects in this area.',
  },
  reeves: {
    name: '93 & 95 Reeves Road',
    location: 'Pakuranga, Auckland',
    category: 'Completed Homes',
    statusClass: 'status-completed',
    statusLabel: 'Completed',
    cardImage: 'img/93-95-reeves-road/photo_1.jpg',
    heroImage: 'img/93-95-reeves-road/photo_1.jpg',
    cardDesc: 'A completed residential development at 93 & 95 Reeves Road, Pakuranga, delivering quality homes in a well-established and highly connected Auckland eastern suburb.',
    overviewTitle: '93 & 95 Reeves Road, Pakuranga',
    overviewBody: `<p><strong>93 & 95 Reeves Road</strong> is a completed dual-site residential development in Pakuranga. Reeves Road is a well-regarded address in Auckland's eastern corridor, with convenient access to the motorway network, Pakuranga Town Centre, and quality local schools. This project delivered a selection of beautifully finished homes that represent strong value in a highly sought-after location.</p>`,
    specs: [
      { label: 'Address', value: '93 & 95 Reeves Road, Pakuranga' },
      { label: 'Status', value: 'Completed' },
    ],
    highlights: [
      { title: 'Established Suburb', body: 'Located on one of Pakuranga\'s most well-regarded roads with excellent access to motorways, schools, and amenities.' },
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
    ],
    images: [
      'img/93-95-reeves-road/photo_1.jpg',
      'img/93-95-reeves-road/photo_2.jpg',
      'img/93-95-reeves-road/photo_3.jpg',
      'img/93-95-reeves-road/photo_4.jpg',
      'img/93-95-reeves-road/photo_5.jpg',
    ],
    enquireTitle: 'Get In Touch — 93 & 95 Reeves Road',
    enquireBody: 'This development is now complete. Contact our team to learn more about future projects in this area.',
  },
  bacot: {
    name: '6 Bacot Place',
    location: 'Howick, Auckland',
    category: 'Completed Homes',
    statusClass: 'status-completed',
    statusLabel: 'Completed',
    cardImage: 'img/6-bacot-place/DSC05655.jpg',
    heroImage: 'img/6-bacot-place/DSC05655.jpg',
    cardDesc: 'A completed residential development at 6 Bacot Place, Howick, delivering quality homes in one of Auckland\'s most established and desirable eastern suburbs.',
    overviewTitle: '6 Bacot Place, Howick',
    overviewBody: `<p><strong>6 Bacot Place</strong> is a completed residential development nestled in the prestigious suburb of Howick, Auckland. With its cul-de-sac setting, this project delivered a quality collection of homes in a quiet, family-friendly environment. Residents enjoy access to Howick Village, top-tier schooling, and easy coastal access — all within a beautifully finished development that reflects the high standards Krown Properties is known for.</p>`,
    specs: [
      { label: 'Address', value: '6 Bacot Place, Howick' },
      { label: 'Status', value: 'Completed' },
    ],
    highlights: [
      { title: 'Quiet Setting', body: 'Situated on a cul-de-sac in prestigious Howick, offering privacy and a strong family-friendly environment.' },
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
    ],
    images: [
      'img/6-bacot-place/DSC05655.jpg',
      'img/6-bacot-place/DSC05658.jpg',
      'img/6-bacot-place/DSC05671.jpg',
      'img/6-bacot-place/DSC05676.jpg',
      'img/6-bacot-place/DSC05679.jpg',
      'img/6-bacot-place/DSC05680.jpg',
      'img/6-bacot-place/DSC05685.jpg',
      'img/6-bacot-place/DSC05689.jpg',
      'img/6-bacot-place/DSC05694.jpg',
      'img/6-bacot-place/DSC05697.jpg',
      'img/6-bacot-place/DSC06067.jpg',
      'img/6-bacot-place/DSC06070.jpg',
      'img/6-bacot-place/DSC06073.jpg',
      'img/6-bacot-place/DSC06081.jpg',
      'img/6-bacot-place/DSC06084.jpg',
      'img/6-bacot-place/DSC06085.jpg',
      'img/6-bacot-place/DSC06090.jpg',
      'img/6-bacot-place/DSC06093.jpg',
      'img/6-bacot-place/DSC06099.jpg',
      'img/6-bacot-place/DSC06105.jpg',
      'img/6-bacot-place/DSC06108.jpg',
      'img/6-bacot-place/DSC06111.jpg',
      'img/6-bacot-place/DSC06112.jpg',
      'img/6-bacot-place/DSC06117.jpg',
      'img/6-bacot-place/DSC06121.jpg',
      'img/6-bacot-place/DSC06126.jpg',
      'img/6-bacot-place/DSC06132.jpg',
      'img/6-bacot-place/DSC06165.jpg',
    ],
    enquireTitle: 'Get In Touch — 6 Bacot Place',
    enquireBody: 'This development is now complete. Contact our team to learn more about future projects in this area.',
  },
  rice: {
    name: '29 Rice Crescent',
    location: 'Papakura, Auckland',
    category: 'Completed Homes',
    statusClass: 'status-completed',
    statusLabel: 'Completed',
    cardImage: 'img/29-rice-crescent/6q27g.jpg',
    heroImage: 'img/29-rice-crescent/6q27g.jpg',
    cardDesc: 'A quality completed development at 29 Rice Crescent, Papakura, delivering well-designed homes in one of Auckland\'s most dynamic southern growth corridors.',
    overviewTitle: '29 Rice Crescent, Papakura',
    overviewBody: `<p><strong>29 Rice Crescent</strong> is a completed residential development in Papakura, South Auckland. Papakura has emerged as one of Auckland's most dynamic growth corridors, benefiting from rail connectivity, motorway access, and significant housing investment. This project delivered a collection of quality homes with modern finishes and practical layouts — now successfully occupied by residents who value both affordability and connectivity.</p>`,
    specs: [
      { label: 'Address', value: '29 Rice Crescent, Papakura' },
      { label: 'Status', value: 'Completed' },
    ],
    highlights: [
      { title: 'Growth Corridor', body: 'Papakura offers rail connectivity, SH1 access, and strong long-term capital growth fundamentals.' },
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
    ],
    images: [
      'img/29-rice-crescent/6q27g.jpg',
      'img/29-rice-crescent/6q27h.jpg',
      'img/29-rice-crescent/6q27j.jpg',
      'img/29-rice-crescent/6q27k.jpg',
      'img/29-rice-crescent/6q27m.jpg',
      'img/29-rice-crescent/6q27n.jpg',
      'img/29-rice-crescent/6q27p.jpg',
      'img/29-rice-crescent/6q27q.jpg',
      'img/29-rice-crescent/6q27r.jpg',
    ],
    enquireTitle: 'Get In Touch — 29 Rice Crescent',
    enquireBody: 'This development is now complete. Contact our team to learn more about future projects in this area.',
  },
  thomas: {
    name: '116 Thomas Road',
    location: 'Flatbush, Auckland',
    category: 'Completed Homes',
    statusClass: 'status-completed',
    statusLabel: 'Completed',
    cardImage: 'https://reliancehomes.co.nz/wp-content/uploads/2025/05/1fe1cb49-0016-47a4-9745-085d4847c28a-1.jpg',
    heroImage: 'https://reliancehomes.co.nz/wp-content/uploads/2025/05/1fe1cb49-0016-47a4-9745-085d4847c28a-1.jpg',
    cardDesc: 'A completed residential development at 116 Thomas Road, Flatbush, delivering contemporary homes with quality finishes in one of South Auckland\'s fastest-growing communities.',
    overviewTitle: '116 Thomas Road, Flatbush',
    overviewBody: `<p><strong>116 Thomas Road</strong> is a completed residential development in Flatbush, one of Auckland's most rapidly expanding southern communities. This project delivered a range of modern homes featuring spacious interiors, quality kitchen and bathroom specifications, and private outdoor areas. With the Flatbush area continuing to grow in infrastructure, schooling, and retail, this development offers strong long-term investment foundations.</p>`,
    specs: [
      { label: 'Address', value: '116 Thomas Road, Flatbush' },
      { label: 'Status', value: 'Completed' },
    ],
    highlights: [
      { title: 'Strong Growth Area', body: 'Flatbush is one of Auckland\'s highest-growth southern suburbs with continued infrastructure and community investment.' },
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
    ],
    images: ['https://reliancehomes.co.nz/wp-content/uploads/2025/05/1fe1cb49-0016-47a4-9745-085d4847c28a-1.jpg'],
    enquireTitle: 'Get In Touch — 116 Thomas Road',
    enquireBody: 'This development is now complete. Contact our team to learn more about future projects in this area.',
  },
  johnwalker: {
    name: '13 John Walker Drive',
    location: 'Manurewa, Auckland',
    category: 'Completed Homes',
    statusClass: 'status-completed',
    statusLabel: 'Completed',
    cardImage: 'https://reliancehomes.co.nz/wp-content/uploads/2025/05/1-1-2.jpg',
    heroImage: 'https://reliancehomes.co.nz/wp-content/uploads/2025/05/1-1-2.jpg',
    cardDesc: 'A completed residential development at 13 John Walker Drive, Manurewa, delivering quality homes in a well-connected and growing South Auckland community.',
    overviewTitle: '13 John Walker Drive, Manurewa',
    overviewBody: `<p><strong>13 John Walker Drive</strong> is a completed residential development in Manurewa, South Auckland. Named after New Zealand's Olympic gold medallist, John Walker Drive is part of a well-planned residential precinct offering strong community infrastructure. This project delivered quality homes with modern finishes in a location that provides excellent motorway and rail access, making it a popular choice for families and commuters alike.</p>`,
    specs: [
      { label: 'Address', value: '13 John Walker Drive, Manurewa' },
      { label: 'Status', value: 'Completed' },
    ],
    highlights: [
      { title: 'Planned Community', body: 'Part of a well-planned residential precinct in Manurewa with strong community facilities and transport links.' },
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
    ],
    images: ['https://reliancehomes.co.nz/wp-content/uploads/2025/05/1-1-2.jpg'],
    enquireTitle: 'Get In Touch — 13 John Walker Drive',
    enquireBody: 'This development is now complete. Contact our team to learn more about future projects in this area.',
  },
  fernaig24: {
    name: '24 Fernaig Street',
    location: 'Papakura, Auckland',
    category: 'Completed Homes',
    statusClass: 'status-completed',
    statusLabel: 'Completed',
    cardImage: 'https://reliancehomes.co.nz/wp-content/uploads/2025/05/2-2.jpg',
    heroImage: 'https://reliancehomes.co.nz/wp-content/uploads/2025/05/2-2.jpg',
    cardDesc: 'A completed residential development at 24 Fernaig Street, Papakura, delivering well-finished homes in one of Auckland\'s most connected southern growth corridors.',
    overviewTitle: '24 Fernaig Street, Papakura',
    overviewBody: `<p><strong>24 Fernaig Street</strong> is a completed residential development in Papakura, South Auckland. This project is part of Krown Properties' broader presence in the Papakura area — a suburb benefitting from significant housing demand, excellent Southern Motorway access, and a growing community infrastructure. The development delivered quality, well-finished homes that represent outstanding value for owner-occupiers and investors.</p>`,
    specs: [
      { label: 'Address', value: '24 Fernaig Street, Papakura' },
      { label: 'Status', value: 'Completed' },
    ],
    highlights: [
      { title: 'High Demand Location', body: 'Papakura continues to attract strong buyer demand driven by affordability, connectivity, and growth fundamentals.' },
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
    ],
    images: ['https://reliancehomes.co.nz/wp-content/uploads/2025/05/2-2.jpg'],
    enquireTitle: 'Get In Touch — 24 Fernaig Street',
    enquireBody: 'This development is now complete. Contact our team to learn more about future projects in this area.',
  },
  fernaig31: {
    name: '31 Fernaig Street',
    location: 'Papakura, Auckland',
    category: 'Completed Homes',
    statusClass: 'status-completed',
    statusLabel: 'Completed',
    cardImage: 'https://reliancehomes.co.nz/wp-content/uploads/2025/05/5-2.jpg',
    heroImage: 'https://reliancehomes.co.nz/wp-content/uploads/2025/05/5-2.jpg',
    cardDesc: 'A completed residential development at 31 Fernaig Street, Papakura, delivering quality homes with modern finishes in a high-demand South Auckland location.',
    overviewTitle: '31 Fernaig Street, Papakura',
    overviewBody: `<p><strong>31 Fernaig Street</strong> is a completed residential development in Papakura, South Auckland. Complementing Krown Properties' neighbouring development at 24 Fernaig Street, this project delivered an additional collection of quality homes in the same well-regarded street. The development underscores Krown Properties' track record of successfully delivering multiple projects within growing communities, consistently meeting the high expectations of buyers and investors.</p>`,
    specs: [
      { label: 'Address', value: '31 Fernaig Street, Papakura' },
      { label: 'Status', value: 'Completed' },
    ],
    highlights: [
      { title: 'Proven Track Record', body: 'Part of Krown Properties\' portfolio in Papakura — demonstrating consistent delivery across multiple projects in the same community.' },
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
    ],
    images: ['https://reliancehomes.co.nz/wp-content/uploads/2025/05/5-2.jpg'],
    enquireTitle: 'Get In Touch — 31 Fernaig Street',
    enquireBody: 'This development is now complete. Contact our team to learn more about future projects in this area.',
  },
  mountain: {
    name: '100 Mountain Road',
    location: 'Epsom, Auckland',
    category: 'Current Projects',
    statusClass: 'status-coming',
    statusLabel: 'Upcoming',
    units: 3, beds: '4–5', baths: 3,
    cardImage: 'img/100-mountain-road/100MountainRoad_exterior1.jpg',
    heroImage: 'img/100-mountain-road/100MountainRoad_exterior1.jpg',
    cardDesc: 'A prestigious residential development at 100 Mountain Road in Epsom delivering architecturally considered homes in one of Auckland\'s most sought-after suburbs.',
    overviewTitle: '100 Mountain Road',
    overviewBody: `<p>Set in the prestigious suburb of Epsom, central Auckland, <strong>100 Mountain Road</strong> represents a rare opportunity to secure a new-build home in one of the city's most coveted addresses. Epsom is celebrated for its top-performing school zones, leafy streets, and proximity to the CBD, Newmarket, and Royal Oak. This upcoming development will deliver a limited collection of architecturally considered residences featuring premium finishes, generous proportions, and refined design details — crafted for buyers who demand the very best. With exceptional long-term capital growth fundamentals, 100 Mountain Road is an investment in both lifestyle and legacy.</p>`,
    specs: [
      { label: 'Address', value: '100 Mountain Road' },
      { label: 'Status', value: 'Upcoming' },
    ],
    highlights: [
      { title: 'Quality Construction', body: 'Built to Krown Properties\' high standards with quality materials and careful attention to detail throughout.' },
      { title: 'Register Your Interest', body: 'Contact our team to receive updates on this development, including pricing and availability.' },
    ],
    images: [
      'img/100-mountain-road/100MountainRoad_exterior1.jpg',
      'img/100-mountain-road/100MountainRoad_exterior2.jpg',
      'img/100-mountain-road/100MountainRoad_exterior3.jpg',
      'img/100-mountain-road/100MountainRoad_exterior4.jpg',
      'img/100-mountain-road/100MountainRoad_exterior5.jpg',
      'img/100-mountain-road/100MountainRoad_exterior6.jpg',
      'img/100-mountain-road/100MountainRoad_exterior7.jpg',
    ],
    enquireTitle: 'Register Interest — 100 Mountain Road',
    enquireBody: 'Register your interest to receive updates on this development, including pricing and availability.',
  },
};
